name: Copy&Modification
on: 
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
jobs:
    shaolin-kongfu:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Download files needed
            run: |
              mkdir -p "/opt/shaolin-kongfu/zq/" && mkdir -p "/opt/shaolin-kongfu/jc/"
              sudo chown -R runner:runner "/opt/shaolin-kongfu/"
              git clone "https://github.com/shaolin-kongfu/js_scripts.git" "/opt/shaolin-kongfu/js_scripts/"
          - name: Modify files
            run: |
              find "/opt/shaolin-kongfu/js_scripts/zq" -name "*.json" | xargs -I {} cp {} "/opt/shaolin-kongfu/zq/"
              ls "/opt/shaolin-kongfu/zq/"
              find "/opt/shaolin-kongfu/js_scripts/" -name "*jc*.json" | xargs -I {} cp {} "/opt/shaolin-kongfu/jc/"
              ls "/opt/shaolin-kongfu/jc/"
              ls "/opt/shaolin-kongfu/zq/" | xargs -I {} sed -i 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
              ls "/opt/shaolin-kongfu/jc/" | xargs -I {} sed -i 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
          - name: Send back
            run:
              cp -f "/opt/shaolin-kongfu/zq/*" "${GITHUB_WORKSPACE}/shaolin-kongfu/"
