name: Copy&Modification
on: 
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
jobs:
    shaolin-kongfu:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Install dependency
            run: |
              sudo -E apt update -y
              sudo -E apt install -y git
          - name: Download files needed
            run: |
              mkdir -p "/opt/shaolin-kongfu/zq" && mkdir -p "/opt/shaolin-kongfu/jc"
              sudo chmod -R +x shaolin-kongfu
              cd "/opt/shaolin-kongfu/"
              git clone -branch "main" "https://github.com/shaolin-kongfu/js_scripts.git"
          - name: Modify files
            run: |
              ls "/opt/shaolin-kongfu/js_scripts/zq/" | grep "*.json" | cp {} "/opt/shaolin-kongfu/zq/"
              ls "/opt/shaolin-kongfu/js_scripts/" | grep "jc|*.json" | cp {} "/opt/shaolin-kongfu/jc/"
              cd "/opt/shaolin-kongfu/zq/"
              ls | grep "*.json" | sed 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
              cd "/opt/shaolin-kongfu/jc/"
              ls | grep "*.json" | sed 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
          - name: Send back
            run:
              cp -f "/opt/shaolin-kongfu/js_scripts/zq/*" "${GITHUB_WORKSPACE}/shaolin-kongfu/"
